In [13]:
# importing the library
import numpy as np

#creating the input array (XOR gate)
X=np.array([[0,0,0,1],[1,0,1,0],[0,1,0,1]])
print ('\n Input:')
print(X)

# creating the output array
y=np.array([[1],[0],[0]])
print('\n Actual Output:')

print(y)

#defining the Sigmoid Function
def sigmoid (x):
    return 1/(1+ np.exp(-x))

# derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x *(1-x)

# initializing the variables
epoch=5000 #number of training iterations
lr=0.1 # learning rate
inputlayer_neurons = X.shape[1] # number of features in data set
hiddenlayer_neurons =3 # number of hidden layers neurons
output_neurons = 1 # number of neurons at output layer.

# initializing weight and bias
wh=np.random.uniform(size=(inputlayer_neurons, hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size= (hiddenlayer_neurons, output_neurons))
bout=np.random.uniform(size=(1, output_neurons))

print("\nBeginning Randomly Generated Weights and Bias: ")
print(wh)
print(bh)
print(wout)
print(bout)

#training the model
for i in range(epoch):
    #Forward Propogation
    hidden_layer_input1=np.dot(X, wh)
    hidden_layer_input=hidden_layer_input1+ bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1=np.dot(hiddenlayer_activations, wout)
    output_layer_input= output_layer_input1+ bout
    output= sigmoid(output_layer_input)
    #Backpropagation
    E = y-output
    slope_output_layer= derivatives_sigmoid(output)
    slope_hidden_layer= derivatives_sigmoid(hiddenlayer_activations)
    d_output= E*slope_output_layer
    Error_at_hidden_layer=d_output.dot(wout.T)
    d_hiddenlayer=Error_at_hidden_layer*slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output)*lr
    bout += np.sum(d_output, axis=0, keepdims=True)*lr
    wh += X.T.dot (d_hiddenlayer)*lr
    bh+= np.sum(d_hiddenlayer, axis=0, keepdims=True)*lr
    
print("\nEnding Weights After Training: ")
print(wh)
print(bh)
print(wout)
print(bout)

print ('\n Output from the model:')
print (output)


 Input:
[[0 0 0 1]
 [1 0 1 0]
 [0 1 0 1]]

 Actual Output:
[[1]
 [0]
 [0]]

Beginning Randomly Generated Weights and Bias: 
[[0.47596149 0.39729593 0.95269984]
 [0.74544376 0.15430305 0.81326961]
 [0.06685454 0.00783643 0.99648534]
 [0.63202979 0.31578378 0.54183454]]
[[0.79568018 0.12480917 0.3017894 ]]
[[0.63745474]
 [0.16509444]
 [0.43561166]]
[[0.61256017]]

Ending Weights After Training: 
[[ 0.1391917   1.05194358  1.70293769]
 [ 0.34996957  2.08446711  4.50013196]
 [-0.26991524  0.66248409  1.7467232 ]
 [ 1.21620715 -0.85945797 -1.44303271]]
[[ 1.04308775 -0.39578492 -0.93283999]]
[[ 1.6686243 ]
 [-2.21535559]
 [-5.95023003]]
[[2.26245729]]

 Output from the model:
[[0.94135684]
 [0.0218707 ]
 [0.04563249]]
